### ISSUE TITLE
Resource selector should include search for ID

### ISSUE THREAD

**Issue by frischnetz** [SEDAdigital/CopyContent#3]
In a site with literally thousends of pages with similar names, the list of resources can become very long. This would be much easier if one could just enter the ID.

**Comment by neoneddy** [comment]
+1

**Comment by neoneddy** [comment]
@frischnetz  I found a solution.  In looking at the code that generates the pick list, the ID is a search factor, but doesn't work great.  For our purposes having it work only with ID, was fine, in fact preferred. 

So what I did was look at the JS connector assets/components/copycontent/js/copycontent.js

Line 53
```            xtype: 'copycontent-combo-resource' ```
To 
```            xtype: 'textfield' ```
Clear cache and try again.  Worked great for us.

**Comment by rtripault** [comment]
Sorry it took us some time to react on that one... another option (which we will ship ASAP) would be to edit the "searchResource" processor with something like (beware, that also ships compatibility changes to make the component work on Revo 3

```
    public function prepareQueryBeforeCount(xPDOQuery $c)
    {
        $c->leftJoin(modContext::class, 'Context');

        $query = $this->getProperty('query');
        $current = $this->getProperty('current');
        if ($current) {
            $c->where([
                'AND:id:!=' => $current,
            ]);
        }
        if (!empty($query)) {
            if (is_numeric($query)) {
                $c->where([
                    'id' => $query,
                ]);

                return $c;
            }


            $c->where([
                'pagetitle:LIKE' => "%$query%",
                'OR:longtitle:LIKE' => "%$query%",
                'OR:uri:LIKE' => "%$query%",
            ]);
        }

        return $c;
    }
```

This should allow entering the ID of the direct resource, as well as prevent doing a LIKE search on the resource ID (which does not feel like a valuable addition).

Hoping that helps
