### ISSUE TITLE
Revo 3 compatiblity

### ISSUE THREAD

**Issue by rtripault** [SEDAdigital/CopyContent#5]
Make it work with Revo 3 as well!

**Comment by ViperAix** [comment]
Will there be an update for MODX 3 soon? :)

**Comment by rtripault** [comment]
Hello there!
As far a i know, we are using it on MODX 3, so current release should work. Are you facing any issue with it ?

Edit: in worse case scenario, we might have patched it manually like in https://github.com/SEDAdigital/CopyContent/commit/1afe3ca83c1aa27f8587a331be12825532afd3d8 (really a few files to change: copycontent.js & searchresource processor)

**Comment by ViperAix** [comment]
I have just tried again, but I get the following error:

![image](https://github.com/SEDAdigital/CopyContent/assets/30976551/f4742308-dc32-424c-b8b0-f033f5e1e4ca)

**Comment by ViperAix** [comment]
> Edit: in worse case scenario, we might have patched it manually like in [1afe3ca](https://github.com/SEDAdigital/CopyContent/commit/1afe3ca83c1aa27f8587a331be12825532afd3d8) (really a few files to change: copycontent.js & searchresource processor)


This is working, thank you.

**Comment by frischnetz** [comment]
The current release is still not working with MODX3. Still the same »Requested processor not found« error. Will there be a proper patched release?

**Comment by fredwardp** [comment]
I would also be grateful for a modx3 update!

**Comment by frischnetz** [comment]
Can I ask really really friendly for a 0.2.0 release? My clients have used CopyContent quite regularily and are not very happy after the update to MODX3 that they cannot use it anymore. Thanks for all your effort in advance!

**Comment by christianseel** [comment]
I pinged @rtripault to upload a new release! I hope we got that this week.

**Comment by rtripault** [comment]
I received the ping! v0.2.0 released a few minutes ago.
Thanks for your patience folks!
